

services:
  postgresql:
    container_name: "oyster_db"
    image: postgres:16.3
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./repositories/src/main/resources/sql:/fixtures
      - ./docker/postgresql/startup.sh:/docker-entrypoint-initdb.d/startup.sh
